/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package puma.thrift.pdp;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class AttributeValueP implements org.apache.thrift.TBase<AttributeValueP, AttributeValueP._Fields>, java.io.Serializable, Cloneable, Comparable<AttributeValueP> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("AttributeValueP");

  private static final org.apache.thrift.protocol.TField DATA_TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("dataType", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField OBJECT_TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("objectType", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField MULTIPLICITY_FIELD_DESC = new org.apache.thrift.protocol.TField("multiplicity", org.apache.thrift.protocol.TType.I32, (short)3);
  private static final org.apache.thrift.protocol.TField ID_FIELD_DESC = new org.apache.thrift.protocol.TField("id", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField STRING_VALUES_FIELD_DESC = new org.apache.thrift.protocol.TField("stringValues", org.apache.thrift.protocol.TType.LIST, (short)5);
  private static final org.apache.thrift.protocol.TField INT_VALUES_FIELD_DESC = new org.apache.thrift.protocol.TField("intValues", org.apache.thrift.protocol.TType.LIST, (short)6);
  private static final org.apache.thrift.protocol.TField DATETIME_VALUES_FIELD_DESC = new org.apache.thrift.protocol.TField("datetimeValues", org.apache.thrift.protocol.TType.LIST, (short)7);
  private static final org.apache.thrift.protocol.TField BOOLEAN_VALUES_FIELD_DESC = new org.apache.thrift.protocol.TField("booleanValues", org.apache.thrift.protocol.TType.LIST, (short)8);
  private static final org.apache.thrift.protocol.TField DOUBLE_VALUES_FIELD_DESC = new org.apache.thrift.protocol.TField("doubleValues", org.apache.thrift.protocol.TType.LIST, (short)9);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new AttributeValuePStandardSchemeFactory());
    schemes.put(TupleScheme.class, new AttributeValuePTupleSchemeFactory());
  }

  /**
   * 
   * @see DataTypeP
   */
  public DataTypeP dataType; // required
  /**
   * 
   * @see ObjectTypeP
   */
  public ObjectTypeP objectType; // required
  /**
   * 
   * @see MultiplicityP
   */
  public MultiplicityP multiplicity; // required
  public String id; // required
  public List<String> stringValues; // optional
  public List<Integer> intValues; // optional
  public List<Long> datetimeValues; // optional
  public List<Boolean> booleanValues; // optional
  public List<Double> doubleValues; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    /**
     * 
     * @see DataTypeP
     */
    DATA_TYPE((short)1, "dataType"),
    /**
     * 
     * @see ObjectTypeP
     */
    OBJECT_TYPE((short)2, "objectType"),
    /**
     * 
     * @see MultiplicityP
     */
    MULTIPLICITY((short)3, "multiplicity"),
    ID((short)4, "id"),
    STRING_VALUES((short)5, "stringValues"),
    INT_VALUES((short)6, "intValues"),
    DATETIME_VALUES((short)7, "datetimeValues"),
    BOOLEAN_VALUES((short)8, "booleanValues"),
    DOUBLE_VALUES((short)9, "doubleValues");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // DATA_TYPE
          return DATA_TYPE;
        case 2: // OBJECT_TYPE
          return OBJECT_TYPE;
        case 3: // MULTIPLICITY
          return MULTIPLICITY;
        case 4: // ID
          return ID;
        case 5: // STRING_VALUES
          return STRING_VALUES;
        case 6: // INT_VALUES
          return INT_VALUES;
        case 7: // DATETIME_VALUES
          return DATETIME_VALUES;
        case 8: // BOOLEAN_VALUES
          return BOOLEAN_VALUES;
        case 9: // DOUBLE_VALUES
          return DOUBLE_VALUES;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private _Fields optionals[] = {_Fields.STRING_VALUES,_Fields.INT_VALUES,_Fields.DATETIME_VALUES,_Fields.BOOLEAN_VALUES,_Fields.DOUBLE_VALUES};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.DATA_TYPE, new org.apache.thrift.meta_data.FieldMetaData("dataType", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, DataTypeP.class)));
    tmpMap.put(_Fields.OBJECT_TYPE, new org.apache.thrift.meta_data.FieldMetaData("objectType", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, ObjectTypeP.class)));
    tmpMap.put(_Fields.MULTIPLICITY, new org.apache.thrift.meta_data.FieldMetaData("multiplicity", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, MultiplicityP.class)));
    tmpMap.put(_Fields.ID, new org.apache.thrift.meta_data.FieldMetaData("id", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.STRING_VALUES, new org.apache.thrift.meta_data.FieldMetaData("stringValues", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    tmpMap.put(_Fields.INT_VALUES, new org.apache.thrift.meta_data.FieldMetaData("intValues", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32))));
    tmpMap.put(_Fields.DATETIME_VALUES, new org.apache.thrift.meta_data.FieldMetaData("datetimeValues", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64))));
    tmpMap.put(_Fields.BOOLEAN_VALUES, new org.apache.thrift.meta_data.FieldMetaData("booleanValues", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL))));
    tmpMap.put(_Fields.DOUBLE_VALUES, new org.apache.thrift.meta_data.FieldMetaData("doubleValues", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(AttributeValueP.class, metaDataMap);
  }

  public AttributeValueP() {
  }

  public AttributeValueP(
    DataTypeP dataType,
    ObjectTypeP objectType,
    MultiplicityP multiplicity,
    String id)
  {
    this();
    this.dataType = dataType;
    this.objectType = objectType;
    this.multiplicity = multiplicity;
    this.id = id;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public AttributeValueP(AttributeValueP other) {
    if (other.isSetDataType()) {
      this.dataType = other.dataType;
    }
    if (other.isSetObjectType()) {
      this.objectType = other.objectType;
    }
    if (other.isSetMultiplicity()) {
      this.multiplicity = other.multiplicity;
    }
    if (other.isSetId()) {
      this.id = other.id;
    }
    if (other.isSetStringValues()) {
      List<String> __this__stringValues = new ArrayList<String>(other.stringValues);
      this.stringValues = __this__stringValues;
    }
    if (other.isSetIntValues()) {
      List<Integer> __this__intValues = new ArrayList<Integer>(other.intValues);
      this.intValues = __this__intValues;
    }
    if (other.isSetDatetimeValues()) {
      List<Long> __this__datetimeValues = new ArrayList<Long>(other.datetimeValues);
      this.datetimeValues = __this__datetimeValues;
    }
    if (other.isSetBooleanValues()) {
      List<Boolean> __this__booleanValues = new ArrayList<Boolean>(other.booleanValues);
      this.booleanValues = __this__booleanValues;
    }
    if (other.isSetDoubleValues()) {
      List<Double> __this__doubleValues = new ArrayList<Double>(other.doubleValues);
      this.doubleValues = __this__doubleValues;
    }
  }

  public AttributeValueP deepCopy() {
    return new AttributeValueP(this);
  }

  @Override
  public void clear() {
    this.dataType = null;
    this.objectType = null;
    this.multiplicity = null;
    this.id = null;
    this.stringValues = null;
    this.intValues = null;
    this.datetimeValues = null;
    this.booleanValues = null;
    this.doubleValues = null;
  }

  /**
   * 
   * @see DataTypeP
   */
  public DataTypeP getDataType() {
    return this.dataType;
  }

  /**
   * 
   * @see DataTypeP
   */
  public AttributeValueP setDataType(DataTypeP dataType) {
    this.dataType = dataType;
    return this;
  }

  public void unsetDataType() {
    this.dataType = null;
  }

  /** Returns true if field dataType is set (has been assigned a value) and false otherwise */
  public boolean isSetDataType() {
    return this.dataType != null;
  }

  public void setDataTypeIsSet(boolean value) {
    if (!value) {
      this.dataType = null;
    }
  }

  /**
   * 
   * @see ObjectTypeP
   */
  public ObjectTypeP getObjectType() {
    return this.objectType;
  }

  /**
   * 
   * @see ObjectTypeP
   */
  public AttributeValueP setObjectType(ObjectTypeP objectType) {
    this.objectType = objectType;
    return this;
  }

  public void unsetObjectType() {
    this.objectType = null;
  }

  /** Returns true if field objectType is set (has been assigned a value) and false otherwise */
  public boolean isSetObjectType() {
    return this.objectType != null;
  }

  public void setObjectTypeIsSet(boolean value) {
    if (!value) {
      this.objectType = null;
    }
  }

  /**
   * 
   * @see MultiplicityP
   */
  public MultiplicityP getMultiplicity() {
    return this.multiplicity;
  }

  /**
   * 
   * @see MultiplicityP
   */
  public AttributeValueP setMultiplicity(MultiplicityP multiplicity) {
    this.multiplicity = multiplicity;
    return this;
  }

  public void unsetMultiplicity() {
    this.multiplicity = null;
  }

  /** Returns true if field multiplicity is set (has been assigned a value) and false otherwise */
  public boolean isSetMultiplicity() {
    return this.multiplicity != null;
  }

  public void setMultiplicityIsSet(boolean value) {
    if (!value) {
      this.multiplicity = null;
    }
  }

  public String getId() {
    return this.id;
  }

  public AttributeValueP setId(String id) {
    this.id = id;
    return this;
  }

  public void unsetId() {
    this.id = null;
  }

  /** Returns true if field id is set (has been assigned a value) and false otherwise */
  public boolean isSetId() {
    return this.id != null;
  }

  public void setIdIsSet(boolean value) {
    if (!value) {
      this.id = null;
    }
  }

  public int getStringValuesSize() {
    return (this.stringValues == null) ? 0 : this.stringValues.size();
  }

  public java.util.Iterator<String> getStringValuesIterator() {
    return (this.stringValues == null) ? null : this.stringValues.iterator();
  }

  public void addToStringValues(String elem) {
    if (this.stringValues == null) {
      this.stringValues = new ArrayList<String>();
    }
    this.stringValues.add(elem);
  }

  public List<String> getStringValues() {
    return this.stringValues;
  }

  public AttributeValueP setStringValues(List<String> stringValues) {
    this.stringValues = stringValues;
    return this;
  }

  public void unsetStringValues() {
    this.stringValues = null;
  }

  /** Returns true if field stringValues is set (has been assigned a value) and false otherwise */
  public boolean isSetStringValues() {
    return this.stringValues != null;
  }

  public void setStringValuesIsSet(boolean value) {
    if (!value) {
      this.stringValues = null;
    }
  }

  public int getIntValuesSize() {
    return (this.intValues == null) ? 0 : this.intValues.size();
  }

  public java.util.Iterator<Integer> getIntValuesIterator() {
    return (this.intValues == null) ? null : this.intValues.iterator();
  }

  public void addToIntValues(int elem) {
    if (this.intValues == null) {
      this.intValues = new ArrayList<Integer>();
    }
    this.intValues.add(elem);
  }

  public List<Integer> getIntValues() {
    return this.intValues;
  }

  public AttributeValueP setIntValues(List<Integer> intValues) {
    this.intValues = intValues;
    return this;
  }

  public void unsetIntValues() {
    this.intValues = null;
  }

  /** Returns true if field intValues is set (has been assigned a value) and false otherwise */
  public boolean isSetIntValues() {
    return this.intValues != null;
  }

  public void setIntValuesIsSet(boolean value) {
    if (!value) {
      this.intValues = null;
    }
  }

  public int getDatetimeValuesSize() {
    return (this.datetimeValues == null) ? 0 : this.datetimeValues.size();
  }

  public java.util.Iterator<Long> getDatetimeValuesIterator() {
    return (this.datetimeValues == null) ? null : this.datetimeValues.iterator();
  }

  public void addToDatetimeValues(long elem) {
    if (this.datetimeValues == null) {
      this.datetimeValues = new ArrayList<Long>();
    }
    this.datetimeValues.add(elem);
  }

  public List<Long> getDatetimeValues() {
    return this.datetimeValues;
  }

  public AttributeValueP setDatetimeValues(List<Long> datetimeValues) {
    this.datetimeValues = datetimeValues;
    return this;
  }

  public void unsetDatetimeValues() {
    this.datetimeValues = null;
  }

  /** Returns true if field datetimeValues is set (has been assigned a value) and false otherwise */
  public boolean isSetDatetimeValues() {
    return this.datetimeValues != null;
  }

  public void setDatetimeValuesIsSet(boolean value) {
    if (!value) {
      this.datetimeValues = null;
    }
  }

  public int getBooleanValuesSize() {
    return (this.booleanValues == null) ? 0 : this.booleanValues.size();
  }

  public java.util.Iterator<Boolean> getBooleanValuesIterator() {
    return (this.booleanValues == null) ? null : this.booleanValues.iterator();
  }

  public void addToBooleanValues(boolean elem) {
    if (this.booleanValues == null) {
      this.booleanValues = new ArrayList<Boolean>();
    }
    this.booleanValues.add(elem);
  }

  public List<Boolean> getBooleanValues() {
    return this.booleanValues;
  }

  public AttributeValueP setBooleanValues(List<Boolean> booleanValues) {
    this.booleanValues = booleanValues;
    return this;
  }

  public void unsetBooleanValues() {
    this.booleanValues = null;
  }

  /** Returns true if field booleanValues is set (has been assigned a value) and false otherwise */
  public boolean isSetBooleanValues() {
    return this.booleanValues != null;
  }

  public void setBooleanValuesIsSet(boolean value) {
    if (!value) {
      this.booleanValues = null;
    }
  }

  public int getDoubleValuesSize() {
    return (this.doubleValues == null) ? 0 : this.doubleValues.size();
  }

  public java.util.Iterator<Double> getDoubleValuesIterator() {
    return (this.doubleValues == null) ? null : this.doubleValues.iterator();
  }

  public void addToDoubleValues(double elem) {
    if (this.doubleValues == null) {
      this.doubleValues = new ArrayList<Double>();
    }
    this.doubleValues.add(elem);
  }

  public List<Double> getDoubleValues() {
    return this.doubleValues;
  }

  public AttributeValueP setDoubleValues(List<Double> doubleValues) {
    this.doubleValues = doubleValues;
    return this;
  }

  public void unsetDoubleValues() {
    this.doubleValues = null;
  }

  /** Returns true if field doubleValues is set (has been assigned a value) and false otherwise */
  public boolean isSetDoubleValues() {
    return this.doubleValues != null;
  }

  public void setDoubleValuesIsSet(boolean value) {
    if (!value) {
      this.doubleValues = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case DATA_TYPE:
      if (value == null) {
        unsetDataType();
      } else {
        setDataType((DataTypeP)value);
      }
      break;

    case OBJECT_TYPE:
      if (value == null) {
        unsetObjectType();
      } else {
        setObjectType((ObjectTypeP)value);
      }
      break;

    case MULTIPLICITY:
      if (value == null) {
        unsetMultiplicity();
      } else {
        setMultiplicity((MultiplicityP)value);
      }
      break;

    case ID:
      if (value == null) {
        unsetId();
      } else {
        setId((String)value);
      }
      break;

    case STRING_VALUES:
      if (value == null) {
        unsetStringValues();
      } else {
        setStringValues((List<String>)value);
      }
      break;

    case INT_VALUES:
      if (value == null) {
        unsetIntValues();
      } else {
        setIntValues((List<Integer>)value);
      }
      break;

    case DATETIME_VALUES:
      if (value == null) {
        unsetDatetimeValues();
      } else {
        setDatetimeValues((List<Long>)value);
      }
      break;

    case BOOLEAN_VALUES:
      if (value == null) {
        unsetBooleanValues();
      } else {
        setBooleanValues((List<Boolean>)value);
      }
      break;

    case DOUBLE_VALUES:
      if (value == null) {
        unsetDoubleValues();
      } else {
        setDoubleValues((List<Double>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case DATA_TYPE:
      return getDataType();

    case OBJECT_TYPE:
      return getObjectType();

    case MULTIPLICITY:
      return getMultiplicity();

    case ID:
      return getId();

    case STRING_VALUES:
      return getStringValues();

    case INT_VALUES:
      return getIntValues();

    case DATETIME_VALUES:
      return getDatetimeValues();

    case BOOLEAN_VALUES:
      return getBooleanValues();

    case DOUBLE_VALUES:
      return getDoubleValues();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case DATA_TYPE:
      return isSetDataType();
    case OBJECT_TYPE:
      return isSetObjectType();
    case MULTIPLICITY:
      return isSetMultiplicity();
    case ID:
      return isSetId();
    case STRING_VALUES:
      return isSetStringValues();
    case INT_VALUES:
      return isSetIntValues();
    case DATETIME_VALUES:
      return isSetDatetimeValues();
    case BOOLEAN_VALUES:
      return isSetBooleanValues();
    case DOUBLE_VALUES:
      return isSetDoubleValues();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof AttributeValueP)
      return this.equals((AttributeValueP)that);
    return false;
  }

  public boolean equals(AttributeValueP that) {
    if (that == null)
      return false;

    boolean this_present_dataType = true && this.isSetDataType();
    boolean that_present_dataType = true && that.isSetDataType();
    if (this_present_dataType || that_present_dataType) {
      if (!(this_present_dataType && that_present_dataType))
        return false;
      if (!this.dataType.equals(that.dataType))
        return false;
    }

    boolean this_present_objectType = true && this.isSetObjectType();
    boolean that_present_objectType = true && that.isSetObjectType();
    if (this_present_objectType || that_present_objectType) {
      if (!(this_present_objectType && that_present_objectType))
        return false;
      if (!this.objectType.equals(that.objectType))
        return false;
    }

    boolean this_present_multiplicity = true && this.isSetMultiplicity();
    boolean that_present_multiplicity = true && that.isSetMultiplicity();
    if (this_present_multiplicity || that_present_multiplicity) {
      if (!(this_present_multiplicity && that_present_multiplicity))
        return false;
      if (!this.multiplicity.equals(that.multiplicity))
        return false;
    }

    boolean this_present_id = true && this.isSetId();
    boolean that_present_id = true && that.isSetId();
    if (this_present_id || that_present_id) {
      if (!(this_present_id && that_present_id))
        return false;
      if (!this.id.equals(that.id))
        return false;
    }

    boolean this_present_stringValues = true && this.isSetStringValues();
    boolean that_present_stringValues = true && that.isSetStringValues();
    if (this_present_stringValues || that_present_stringValues) {
      if (!(this_present_stringValues && that_present_stringValues))
        return false;
      if (!this.stringValues.equals(that.stringValues))
        return false;
    }

    boolean this_present_intValues = true && this.isSetIntValues();
    boolean that_present_intValues = true && that.isSetIntValues();
    if (this_present_intValues || that_present_intValues) {
      if (!(this_present_intValues && that_present_intValues))
        return false;
      if (!this.intValues.equals(that.intValues))
        return false;
    }

    boolean this_present_datetimeValues = true && this.isSetDatetimeValues();
    boolean that_present_datetimeValues = true && that.isSetDatetimeValues();
    if (this_present_datetimeValues || that_present_datetimeValues) {
      if (!(this_present_datetimeValues && that_present_datetimeValues))
        return false;
      if (!this.datetimeValues.equals(that.datetimeValues))
        return false;
    }

    boolean this_present_booleanValues = true && this.isSetBooleanValues();
    boolean that_present_booleanValues = true && that.isSetBooleanValues();
    if (this_present_booleanValues || that_present_booleanValues) {
      if (!(this_present_booleanValues && that_present_booleanValues))
        return false;
      if (!this.booleanValues.equals(that.booleanValues))
        return false;
    }

    boolean this_present_doubleValues = true && this.isSetDoubleValues();
    boolean that_present_doubleValues = true && that.isSetDoubleValues();
    if (this_present_doubleValues || that_present_doubleValues) {
      if (!(this_present_doubleValues && that_present_doubleValues))
        return false;
      if (!this.doubleValues.equals(that.doubleValues))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(AttributeValueP other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetDataType()).compareTo(other.isSetDataType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDataType()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.dataType, other.dataType);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetObjectType()).compareTo(other.isSetObjectType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetObjectType()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.objectType, other.objectType);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetMultiplicity()).compareTo(other.isSetMultiplicity());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMultiplicity()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.multiplicity, other.multiplicity);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetId()).compareTo(other.isSetId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.id, other.id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetStringValues()).compareTo(other.isSetStringValues());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStringValues()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.stringValues, other.stringValues);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetIntValues()).compareTo(other.isSetIntValues());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIntValues()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.intValues, other.intValues);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDatetimeValues()).compareTo(other.isSetDatetimeValues());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDatetimeValues()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.datetimeValues, other.datetimeValues);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetBooleanValues()).compareTo(other.isSetBooleanValues());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBooleanValues()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.booleanValues, other.booleanValues);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDoubleValues()).compareTo(other.isSetDoubleValues());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDoubleValues()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.doubleValues, other.doubleValues);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("AttributeValueP(");
    boolean first = true;

    sb.append("dataType:");
    if (this.dataType == null) {
      sb.append("null");
    } else {
      sb.append(this.dataType);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("objectType:");
    if (this.objectType == null) {
      sb.append("null");
    } else {
      sb.append(this.objectType);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("multiplicity:");
    if (this.multiplicity == null) {
      sb.append("null");
    } else {
      sb.append(this.multiplicity);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("id:");
    if (this.id == null) {
      sb.append("null");
    } else {
      sb.append(this.id);
    }
    first = false;
    if (isSetStringValues()) {
      if (!first) sb.append(", ");
      sb.append("stringValues:");
      if (this.stringValues == null) {
        sb.append("null");
      } else {
        sb.append(this.stringValues);
      }
      first = false;
    }
    if (isSetIntValues()) {
      if (!first) sb.append(", ");
      sb.append("intValues:");
      if (this.intValues == null) {
        sb.append("null");
      } else {
        sb.append(this.intValues);
      }
      first = false;
    }
    if (isSetDatetimeValues()) {
      if (!first) sb.append(", ");
      sb.append("datetimeValues:");
      if (this.datetimeValues == null) {
        sb.append("null");
      } else {
        sb.append(this.datetimeValues);
      }
      first = false;
    }
    if (isSetBooleanValues()) {
      if (!first) sb.append(", ");
      sb.append("booleanValues:");
      if (this.booleanValues == null) {
        sb.append("null");
      } else {
        sb.append(this.booleanValues);
      }
      first = false;
    }
    if (isSetDoubleValues()) {
      if (!first) sb.append(", ");
      sb.append("doubleValues:");
      if (this.doubleValues == null) {
        sb.append("null");
      } else {
        sb.append(this.doubleValues);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class AttributeValuePStandardSchemeFactory implements SchemeFactory {
    public AttributeValuePStandardScheme getScheme() {
      return new AttributeValuePStandardScheme();
    }
  }

  private static class AttributeValuePStandardScheme extends StandardScheme<AttributeValueP> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, AttributeValueP struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // DATA_TYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.dataType = DataTypeP.findByValue(iprot.readI32());
              struct.setDataTypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // OBJECT_TYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.objectType = ObjectTypeP.findByValue(iprot.readI32());
              struct.setObjectTypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // MULTIPLICITY
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.multiplicity = MultiplicityP.findByValue(iprot.readI32());
              struct.setMultiplicityIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.id = iprot.readString();
              struct.setIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // STRING_VALUES
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.stringValues = new ArrayList<String>(_list0.size);
                for (int _i1 = 0; _i1 < _list0.size; ++_i1)
                {
                  String _elem2;
                  _elem2 = iprot.readString();
                  struct.stringValues.add(_elem2);
                }
                iprot.readListEnd();
              }
              struct.setStringValuesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // INT_VALUES
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list3 = iprot.readListBegin();
                struct.intValues = new ArrayList<Integer>(_list3.size);
                for (int _i4 = 0; _i4 < _list3.size; ++_i4)
                {
                  int _elem5;
                  _elem5 = iprot.readI32();
                  struct.intValues.add(_elem5);
                }
                iprot.readListEnd();
              }
              struct.setIntValuesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // DATETIME_VALUES
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list6 = iprot.readListBegin();
                struct.datetimeValues = new ArrayList<Long>(_list6.size);
                for (int _i7 = 0; _i7 < _list6.size; ++_i7)
                {
                  long _elem8;
                  _elem8 = iprot.readI64();
                  struct.datetimeValues.add(_elem8);
                }
                iprot.readListEnd();
              }
              struct.setDatetimeValuesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // BOOLEAN_VALUES
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list9 = iprot.readListBegin();
                struct.booleanValues = new ArrayList<Boolean>(_list9.size);
                for (int _i10 = 0; _i10 < _list9.size; ++_i10)
                {
                  boolean _elem11;
                  _elem11 = iprot.readBool();
                  struct.booleanValues.add(_elem11);
                }
                iprot.readListEnd();
              }
              struct.setBooleanValuesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 9: // DOUBLE_VALUES
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list12 = iprot.readListBegin();
                struct.doubleValues = new ArrayList<Double>(_list12.size);
                for (int _i13 = 0; _i13 < _list12.size; ++_i13)
                {
                  double _elem14;
                  _elem14 = iprot.readDouble();
                  struct.doubleValues.add(_elem14);
                }
                iprot.readListEnd();
              }
              struct.setDoubleValuesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, AttributeValueP struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.dataType != null) {
        oprot.writeFieldBegin(DATA_TYPE_FIELD_DESC);
        oprot.writeI32(struct.dataType.getValue());
        oprot.writeFieldEnd();
      }
      if (struct.objectType != null) {
        oprot.writeFieldBegin(OBJECT_TYPE_FIELD_DESC);
        oprot.writeI32(struct.objectType.getValue());
        oprot.writeFieldEnd();
      }
      if (struct.multiplicity != null) {
        oprot.writeFieldBegin(MULTIPLICITY_FIELD_DESC);
        oprot.writeI32(struct.multiplicity.getValue());
        oprot.writeFieldEnd();
      }
      if (struct.id != null) {
        oprot.writeFieldBegin(ID_FIELD_DESC);
        oprot.writeString(struct.id);
        oprot.writeFieldEnd();
      }
      if (struct.stringValues != null) {
        if (struct.isSetStringValues()) {
          oprot.writeFieldBegin(STRING_VALUES_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.stringValues.size()));
            for (String _iter15 : struct.stringValues)
            {
              oprot.writeString(_iter15);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      if (struct.intValues != null) {
        if (struct.isSetIntValues()) {
          oprot.writeFieldBegin(INT_VALUES_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I32, struct.intValues.size()));
            for (int _iter16 : struct.intValues)
            {
              oprot.writeI32(_iter16);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      if (struct.datetimeValues != null) {
        if (struct.isSetDatetimeValues()) {
          oprot.writeFieldBegin(DATETIME_VALUES_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I64, struct.datetimeValues.size()));
            for (long _iter17 : struct.datetimeValues)
            {
              oprot.writeI64(_iter17);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      if (struct.booleanValues != null) {
        if (struct.isSetBooleanValues()) {
          oprot.writeFieldBegin(BOOLEAN_VALUES_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.BOOL, struct.booleanValues.size()));
            for (boolean _iter18 : struct.booleanValues)
            {
              oprot.writeBool(_iter18);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      if (struct.doubleValues != null) {
        if (struct.isSetDoubleValues()) {
          oprot.writeFieldBegin(DOUBLE_VALUES_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.DOUBLE, struct.doubleValues.size()));
            for (double _iter19 : struct.doubleValues)
            {
              oprot.writeDouble(_iter19);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class AttributeValuePTupleSchemeFactory implements SchemeFactory {
    public AttributeValuePTupleScheme getScheme() {
      return new AttributeValuePTupleScheme();
    }
  }

  private static class AttributeValuePTupleScheme extends TupleScheme<AttributeValueP> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, AttributeValueP struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetDataType()) {
        optionals.set(0);
      }
      if (struct.isSetObjectType()) {
        optionals.set(1);
      }
      if (struct.isSetMultiplicity()) {
        optionals.set(2);
      }
      if (struct.isSetId()) {
        optionals.set(3);
      }
      if (struct.isSetStringValues()) {
        optionals.set(4);
      }
      if (struct.isSetIntValues()) {
        optionals.set(5);
      }
      if (struct.isSetDatetimeValues()) {
        optionals.set(6);
      }
      if (struct.isSetBooleanValues()) {
        optionals.set(7);
      }
      if (struct.isSetDoubleValues()) {
        optionals.set(8);
      }
      oprot.writeBitSet(optionals, 9);
      if (struct.isSetDataType()) {
        oprot.writeI32(struct.dataType.getValue());
      }
      if (struct.isSetObjectType()) {
        oprot.writeI32(struct.objectType.getValue());
      }
      if (struct.isSetMultiplicity()) {
        oprot.writeI32(struct.multiplicity.getValue());
      }
      if (struct.isSetId()) {
        oprot.writeString(struct.id);
      }
      if (struct.isSetStringValues()) {
        {
          oprot.writeI32(struct.stringValues.size());
          for (String _iter20 : struct.stringValues)
          {
            oprot.writeString(_iter20);
          }
        }
      }
      if (struct.isSetIntValues()) {
        {
          oprot.writeI32(struct.intValues.size());
          for (int _iter21 : struct.intValues)
          {
            oprot.writeI32(_iter21);
          }
        }
      }
      if (struct.isSetDatetimeValues()) {
        {
          oprot.writeI32(struct.datetimeValues.size());
          for (long _iter22 : struct.datetimeValues)
          {
            oprot.writeI64(_iter22);
          }
        }
      }
      if (struct.isSetBooleanValues()) {
        {
          oprot.writeI32(struct.booleanValues.size());
          for (boolean _iter23 : struct.booleanValues)
          {
            oprot.writeBool(_iter23);
          }
        }
      }
      if (struct.isSetDoubleValues()) {
        {
          oprot.writeI32(struct.doubleValues.size());
          for (double _iter24 : struct.doubleValues)
          {
            oprot.writeDouble(_iter24);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, AttributeValueP struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(9);
      if (incoming.get(0)) {
        struct.dataType = DataTypeP.findByValue(iprot.readI32());
        struct.setDataTypeIsSet(true);
      }
      if (incoming.get(1)) {
        struct.objectType = ObjectTypeP.findByValue(iprot.readI32());
        struct.setObjectTypeIsSet(true);
      }
      if (incoming.get(2)) {
        struct.multiplicity = MultiplicityP.findByValue(iprot.readI32());
        struct.setMultiplicityIsSet(true);
      }
      if (incoming.get(3)) {
        struct.id = iprot.readString();
        struct.setIdIsSet(true);
      }
      if (incoming.get(4)) {
        {
          org.apache.thrift.protocol.TList _list25 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
          struct.stringValues = new ArrayList<String>(_list25.size);
          for (int _i26 = 0; _i26 < _list25.size; ++_i26)
          {
            String _elem27;
            _elem27 = iprot.readString();
            struct.stringValues.add(_elem27);
          }
        }
        struct.setStringValuesIsSet(true);
      }
      if (incoming.get(5)) {
        {
          org.apache.thrift.protocol.TList _list28 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I32, iprot.readI32());
          struct.intValues = new ArrayList<Integer>(_list28.size);
          for (int _i29 = 0; _i29 < _list28.size; ++_i29)
          {
            int _elem30;
            _elem30 = iprot.readI32();
            struct.intValues.add(_elem30);
          }
        }
        struct.setIntValuesIsSet(true);
      }
      if (incoming.get(6)) {
        {
          org.apache.thrift.protocol.TList _list31 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I64, iprot.readI32());
          struct.datetimeValues = new ArrayList<Long>(_list31.size);
          for (int _i32 = 0; _i32 < _list31.size; ++_i32)
          {
            long _elem33;
            _elem33 = iprot.readI64();
            struct.datetimeValues.add(_elem33);
          }
        }
        struct.setDatetimeValuesIsSet(true);
      }
      if (incoming.get(7)) {
        {
          org.apache.thrift.protocol.TList _list34 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.BOOL, iprot.readI32());
          struct.booleanValues = new ArrayList<Boolean>(_list34.size);
          for (int _i35 = 0; _i35 < _list34.size; ++_i35)
          {
            boolean _elem36;
            _elem36 = iprot.readBool();
            struct.booleanValues.add(_elem36);
          }
        }
        struct.setBooleanValuesIsSet(true);
      }
      if (incoming.get(8)) {
        {
          org.apache.thrift.protocol.TList _list37 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.DOUBLE, iprot.readI32());
          struct.doubleValues = new ArrayList<Double>(_list37.size);
          for (int _i38 = 0; _i38 < _list37.size; ++_i38)
          {
            double _elem39;
            _elem39 = iprot.readDouble();
            struct.doubleValues.add(_elem39);
          }
        }
        struct.setDoubleValuesIsSet(true);
      }
    }
  }

}

